name: untitled
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  google_fonts: ^4.0.3
  flutter:
    sdk: flutter
  get: ^4.1.4
  dots_indicator: ^2.1.0

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
  - assets/image/

flutter_lints: ^2.0.0





